name = "ccc1021-size-of-space"
account_id = "bd967aab2d5f80b6a7f520a460dba284"
compatibility_date = "2026-01-01"
workers_dev = true

[assets]
directory = "./size-of-space"
not_found_handling = "single-page-application"
