import { lyToKm } from './format-size.js';

const h = lyToKm;

function obj(name, rad, type, texture, render = 'sphere') {
  return { name, rad, type, texture, render };
}

export const SPACE_OBJECTS = [
  obj('Astronaut', 0.0016764, '', 'astronaut', 'galaxy'),
  obj('Hubble Space Telescope', 0.0066, 'Man-made Object', 'hubble', 'galaxy'),
  obj('Space Shuttle', 0.0186, 'Man-made Object', 'space-shuttle', 'galaxy'),
  obj('Space Station', 0.054, 'Man-made Object', 'space-station', 'galaxy'),
  obj('Saturn V Rocket', 0.0553, 'Man-made Object', 'saturn-v', 'galaxy'),
  obj('Bennu', 0.8, 'Asteroid', 'bennu', 'galaxy'),
  obj('Deimos', 6.1, 'Moon of Mars', 'deimos', 'galaxy'),
  obj('243 Ida', 15.7, 'Asteroid', '243-Ida', 'galaxy'),
  obj('4 Vesta', 262.5, 'Asteroid', 'vesta', 'galaxy'),
  obj('Ceres', 473, 'Dwarf Planet', 'ceres'),
  obj('MakeMake', 715, 'Dwarf Planet', 'makemake'),
  obj('Pluto', 1195, 'Dwarf Planet', 'pluto'),
  obj('Europa', 1560.8, 'Moon of Jupiter', 'europa'),
  obj('Moon', 1738.1, 'Moon of Earth', 'moon'),
  obj('Io', 1821.6, 'Moon of Jupiter', 'io'),
  obj('Mercury', 2439.7, 'Rocky Planet', 'mercury'),
  obj('Titan', 2574.7, 'Moon of Saturn', 'titan'),
  obj('Mars', 3396.2, 'Rocky Planet', 'mars'),
  obj('Sirius B', 5850, 'White Dwarf Star', 'white-dwarf'),
  obj('Venus', 6051.8, 'Rocky Planet', 'venus'),
  obj('Earth', 6378.1, 'Rocky Planet', 'earth'),
  obj('Kepler-22b', 15290, 'Earth-like Exoplanet', 'kepler-22'),
  obj('Neptune', 24764, 'Ice Giant', 'neptune'),
  obj('Uranus', 25559, 'Ice Giant', 'uranus'),
  obj('Saturn', 120268, 'Gas Giant', 'saturn', 'saturn'),
  obj('Jupiter', 69911, 'Gas Giant', 'jupiter'),
  obj('Sun', 695510, 'Yellow Dwarf Star', 'sun'),
  obj('Sirius A', 119e4, 'Main-Sequence Star', 'white-dwarf'),
  obj('Pollux', 6122200, 'Red Giant Star', 'pollux'),
  obj('Sagittarius A*', 11816117, 'Supermassive Black Hole', 'black-hole', 'blackhole'),
  obj('Arcturus', 17671e3, 'Red Giant Star', 'red-star'),
  obj('Aldebaran', 30701e3, 'Red Giant Star', 'aldebaran'),
  obj('Rigel', 5489e4, 'Blue Supergiant Star', 'blue-star'),
  obj('Pistol Star', 21288e4, 'Blue Hypergiant Star', 'pistol-star'),
  obj('Betelgeuse', 6171e5, 'Red Supergiant Star', 'sun'),
  obj('UY Scuti', 1188e6, 'Red Supergiant Star', 'aldebaran'),
  obj('M87 Black Hole', 19e9, 'Supermassive Black Hole', 'm87', 'galaxy'),
  obj('NGC 3842', 28654083050, 'Supermassive Black Hole', 'black-hole', 'blackhole'),
  obj('Ton 618', 19447723e4, 'Supermassive Black Hole', 'black-hole', 'blackhole'),
  obj("Cat's Eye Nebula", h(0.2), 'Planetary Nebula', 'cats-eye', 'galaxy'),
  obj('Barnard 68', h(0.25), 'Dark Nebula', 'barnard-68', 'galaxy'),
  obj('Ring Nebula', h(1.3), 'Planetary Nebula', 'ring-nebula', 'galaxy'),
  obj('Butterfly Nebula', h(1.5), 'Planetary Nebula', 'butterfly-nebula', 'galaxy'),
  obj('Crab Nebula', h(5.5), 'Supernova Remnant', 'crab-nebula', 'galaxy'),
  obj("Kepler's Supernova", h(7), 'Supernova Remnant', 'kepler-supernova', 'galaxy'),
  obj("Tycho's Supernova", h(17.5), 'Supernova Remnant', 'tycho', 'galaxy'),
  obj('Segue 2', h(110.89), 'Dwarf Spheroidal Galaxy', 'segue-2', 'galaxy'),
  obj('Tarantula Nebula', h(931), 'Emission Nebula', 'tarantula-nebula', 'galaxy'),
  obj("Barnard's Galaxy", h(3500), 'Barred Irregular Galaxy', 'barnards-galaxy', 'galaxy'),
  obj('Fireworks Galaxy', h(2e4), 'Intermediate Spiral Galaxy', 'fireworks-galaxy', 'galaxy'),
  obj('Milky Way Galaxy', h(52850), 'Barred Spiral Galaxy', 'milky_way', 'galaxy'),
  obj("Hoag's Object", h(60500), 'Ring Galaxy', 'hoags_object', 'galaxy'),
  obj('Cartwheel Galaxy', h(65e3), 'Lenticular Galaxy', 'cartwheel-galaxy', 'galaxy'),
  obj('Andromeda Galaxy', h(11e4), 'Spiral Galaxy', 'andromeda-galaxy', 'galaxy'),
  obj('IC 1101', h(1956900), 'Supergiant Elliptical Galaxy', 'ic-1101', 'galaxy'),
  obj('Local Group', h(5e6), 'Galaxy Group', 'local-group', 'galaxy'),
  obj('Virgo Supercluster', h(55e6), 'Galaxy Supercluster', 'virgo-supercluster', 'galaxy'),
  obj('Laniakea Supercluster', h(25e7), 'Galaxy Supercluster', 'laniakea', 'galaxy'),
  obj('Huge LQG', h(2e9), 'Large Quasar Group', 'huge-lgq', 'galaxy'),
  obj('Observable Universe', h(46508e6), '', 'cosmic-background', 'galaxy'),
];
